language: generic

python:
  - '3.8'

services:
  - docker

stages:
  - build
  - test
  - deploy

jobs:
  include:
    ### PULL REQUESTS ###

    - stage: build
      name: Build and push ALL images
      if: branch = master
      before_script:
        - cd express-app
      script:
        - DOCKER_BUILDKIT=1 docker build -t express:latest .