apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret-env
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  HEALTH_TOKEN: {{ .Values.healthToken | b64enc }}