apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  prefix: /
  host: {{ .Values.hostName }}
  service: '{{ include "app.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}'